/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.zxing.client.androidtest;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int status_text=0x7f040001;
        public static final int status_view=0x7f040000;
        public static final int transparent=0x7f040002;
        public static final int viewfinder_frame=0x7f040003;
        public static final int viewfinder_mask=0x7f040004;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int auto_focus=0x7f050000;
        public static final int benchmark_done=0x7f050001;
        public static final int benchmark_help=0x7f050007;
        public static final int benchmark_run=0x7f050006;
        public static final int encode_bad_data=0x7f050015;
        public static final int encode_contact=0x7f050012;
        public static final int encode_email=0x7f05000f;
        public static final int encode_hidden_data=0x7f050014;
        public static final int encode_location=0x7f050013;
        public static final int encode_phone=0x7f050010;
        public static final int encode_sms=0x7f050011;
        public static final int encode_url=0x7f05000e;
        public static final int get_camera_parameters=0x7f050009;
        public static final int quit=0x7f050002;
        public static final int run_benchmark=0x7f050008;
        public static final int save=0x7f050003;
        public static final int save_failed=0x7f050005;
        public static final int save_succeeded=0x7f050004;
        public static final int scan_anything=0x7f05000c;
        public static final int scan_product=0x7f05000a;
        public static final int scan_qr_code=0x7f05000b;
        public static final int search_book_contents=0x7f05000d;
        public static final int share_via_barcode=0x7f050016;
    }
    public static final class layout {
        public static final int benchmark=0x7f030000;
        public static final int test=0x7f030001;
    }
    public static final class string {
        public static final int about_menu=0x7f060000;
        public static final int about_message=0x7f060001;
        public static final int app_name=0x7f060002;
        public static final int benchmark_help=0x7f060004;
        public static final int benchmark_name=0x7f060003;
        public static final int benchmark_run=0x7f060005;
        public static final int benchmark_running=0x7f060006;
        public static final int encode_bad_data=0x7f060007;
        public static final int encode_contact=0x7f060008;
        public static final int encode_email=0x7f060009;
        public static final int encode_hidden_data=0x7f06000a;
        public static final int encode_location=0x7f06000b;
        public static final int encode_phone=0x7f06000c;
        public static final int encode_sms=0x7f06000d;
        public static final int encode_url=0x7f06000e;
        public static final int get_camera_parameters=0x7f06000f;
        public static final int ok_button=0x7f060010;
        public static final int parameters_message=0x7f060011;
        public static final int result_failed=0x7f060012;
        public static final int result_failed_why=0x7f060013;
        public static final int result_succeeded=0x7f060014;
        public static final int save_failed=0x7f060015;
        public static final int save_succeeded=0x7f060016;
        public static final int scan_anything=0x7f060017;
        public static final int scan_product=0x7f060018;
        public static final int scan_qr_code=0x7f060019;
        public static final int search_book_contents=0x7f06001a;
        public static final int share_via_barcode=0x7f06001b;
        public static final int status_message=0x7f06001c;
        public static final int take_test_photos=0x7f06001d;
    }
}
